app: convert js to ts
We need to enable esModuleInterop for SocksProxyAgent
because this solves error TS1192.
The SocksProxyAgent doesn't have default exports.